### PR TITLE
1.5: Update flat-database.h - Correct 'Writting' to 'Writing'

### PR DESCRIPTION
**Pull request by gwestwood**
### What is the purpose of this pull request (PR)?
Correct 'Writting' to 'Writing'.

### CODE REVIEW

**Comment by spencerlievens** [comment]
ACK

**Comment by spencerlievens** [comment]
This will need to be merged to the new version of Dynamic once the branch becomes available.

**Comment by AmirAbrams** [comment]
Added to Pull Request #298

**Comment by AmirAbrams** [comment]
Closing this PR but your commit will be part of v1.5.0.0 (#298).  Thanks again!

**Pull request closed without merging**
