### PR TITLE
Updates PoW to argon2d and adjusts chainparams

### PR DESCRIPTION
**Pull request by GregoryBetz**

### CODE REVIEW

**Comment by AmirAbrams** [comment]
The first commit is too large and not atomic:  https://github.com/duality-solutions/Dynamic/pull/8/commits/dee8eecd5afa0a98b055c1af9c04d71b7b7b2ac1   It should be in 3 separate commits. The others are much more digestible.

**Comment by GregoryBetz** [comment]
Because most of the room that the website allows is taken up by x11 files that had to be deleted. The commit does one thing, therefore it is atomic. But I'll redo it for you lazy people who don't want to click view file

**Comment by AmirAbrams** [comment]
screenshot from 2016-11-20 00-09-50

**Comment by GregoryBetz** [comment]
image

We've got a winner!

**Comment by GregoryBetz** [comment]
MotiRCJYppcwrNPZjnjVDzJR7s9GAHz2QppndLxDMGUL4F8qhC4V

**Comment by spencerlievens** [comment]
ScanHash was doing what MineGenesis was doing prior to Amirs fix. Adding 4bytes to the header and doublesha256 etc.

Removal is one option, adaptation is a better one I believe.

**Comment by GregoryBetz** [comment]
Yep, like I said, we have about 10% of segwit implemented already. ScanHash() is one part. 

As we enable more diverse services, a header message that is variable in a few dimensions, so as to describe the connection type, would be a good addition. Not only is a large global network good, but even better is one that is diverse. Diversity among the network's services encourages decentralization, prosperity, and longevity just as diversity within a genome does. Modularity is key as well. 

Anyway, can you guys focus the review on this commit: https://github.com/duality-solutions/Dynamic/pull/8/commits/d3b28c4288e354aa07d785abc5c933bad8df999e ? It's a delicate one haha.

**Comment by spencerlievens** [comment]
ACK on the Algo and Mining of PoW blocks.

utACK on the budgeting blocks.

Will merge but we need to ensure budgeting blocks are ok.

Also am merging as I know this code was ok with the last iteraton of DarkSilk.

**Pull request merged**
