### PR TITLE
[Sync] Fix issue with chain syncing

### PR DESCRIPTION
**Pull request by AmirAbrams**
### What is the purpose of this pull request (PR)?
Fixes syncing issues when starting with a new chain.  Headers first check work validation was failing because `chainActive.Height()` was used instead of `pindexLast->nHeight`
#### Was this PR tested and how? (If testing is not needed, please explain why)
Yes, but not enough.  Used Ubuntu 16.04.
#### Does this PR resolve an open issue (reference issue #)?
Yes, issue #212

### CODE REVIEW

**Comment by SCDeveloper** [comment]
Have merged to v1.4.0.0 branch.

**Comment by plaxton** [comment]
Spencer, I hate to tell you but I told you so! You don't use chainActive.Height() for difficulty, It looks out of place

**Comment by SCDeveloper** [comment]
Yes you did, I stand corrected :P

**Comment by plaxton** [comment]
ACK

**Comment by SCDeveloper** [comment]
Merged to v1.3.0.2, closing this PR.

**Pull request closed without merging**
