### PR TITLE
Multiple Fixes

### PR DESCRIPTION
**Pull request by spencerlievens**

### CODE REVIEW

**Comment by spencerlievens** [comment]
This Pull Request is now ready for review.

**Comment by ghost** [comment]
Looks Good!

**Comment by AmirAbrams** [comment]
Dynode enabled.
dynamic-fluid-dynode_test3_20171208

**Review by AmirAbrams — APPROVED** [review]
Nice work!

**Comment by AmirAbrams** [comment]
dynamic-fluid-dynode_test5_20171208

dynamic-fluid-dynode_test4_20171208

**Pull request merged**
