### PR TITLE
V1.3.0.0

### PR DESCRIPTION
**Pull request by empinel**

### CODE REVIEW

**Comment by SCDeveloper** [comment]
utACK - Under TestNet.

**Comment by SCDeveloper** [comment]
First test I found it stall at the hard fork block. I have made changes and am testing once more.

**Comment by SCDeveloper** [comment]
DynamicMiner -- runtime error: Division by zero

template <unsigned int BITS>
base_uint<BITS>& base_uint<BITS>::operator/=(const base_uint& b)
{
    base_uint<BITS> div = b;     // make a copy, so we can shift.
    base_uint<BITS> num = *this; // make a copy, so we can subtract.
    *this = 0;                   // the quotient.
    int num_bits = num.bits();
    int div_bits = div.bits();
    if (div_bits == 0)
        throw uint_error("Division by zero");
    if (div_bits > num_bits) // the result is certainly 0.
        return *this;
    int shift = num_bits - div_bits;
    div <<= shift; // shift so that div and num align.
    while (shift >= 0) {
        if (num >= div) {
            num -= div;
            pn[shift / 32] |= (1 << (shift & 31)); // set a bit of the result.
        }
        div >>= 1; // shift back.
        shift--;
    }
    // num now contains the remainder of the division.
    return *this;
} 

This is the function that contains the error message being thrown: arith_uint256.cpp line 95

There is no issue with this function, the error is elsewhere, but relative to base_uint.

**Comment by SCDeveloper** [comment]
Please investigate Ahmad.

**Comment by SCDeveloper** [comment]
OK, Diff Retarget Algo changed for DELTA. Tested on testnet and difficulty adjusts correctly.

MainNet connection is also tested, syncs correctly, Dynode sync does happen but takes longer due to the increased block rate. However, blockchain syncs and wallet mines and blocks are accepted to the blockchain.

ACK.

**Comment by empinel** [comment]
Okay, I'm going to start consolidation now

**Comment by AmirAbrams** [comment]
utACK

**Pull request merged**
