### PR TITLE
V1.2.0.0

### PR DESCRIPTION
**Pull request by SCDeveloper**

### CODE REVIEW

**Comment by coin-info-net** [comment]
ACK

**Comment by SCDeveloper** [comment]
Tested at each commit.

**Comment by AmirAbrams** [comment]
I am testing this repo (argon2d-test branch):  https://github.com/duality-solutions/yiimp

I am able to find blocks on testnet but need to add some Dynodes and run some fluid commands before I am sure it is fully working.

yiimp-working-testnet

**Comment by Duality-CDOO** [comment]
That block reward is correct, it is two vouts. One for the miner and one for the Dynode winner.

1 + 1.618 = 2.618

However, it needs to take fluidIssuance into account because:

CAmount blockAmount = blockReward + fluidIssuance;

**Pull request merged**
